### ISSUE TITLE
Educate students on emailing professors

### ISSUE THREAD

**Issue by sr320** [OARS-SAFS/DEI#16]

**Comment by sr320** [comment]
Where is the best place to provide this information? possibly https://fish.uw.edu/students/graduate-program/prepare-apply/

**Comment by elpetrou** [comment]
I think that would be a great place to put that information. We could also consider hosting a short meeting each fall for undergraduates who are considering applying to grad school, where we share information with them and answer their questions.

**Comment by sr320** [comment]
Created separate issue for hosting meeting with undergraduates
https://github.com/OARS-SAFS/DEI/issues/45

**Comment by sr320** [comment]
via @mdscheuerell as format....

Perhaps this is something we could consider as well.

https://biology.stanford.edu/academics/phd-program/stanford-biology-phd-preview-program

**Comment by sr320** [comment]
covered in video at https://fish.uw.edu/students/graduate-program/prepare-apply/
