### ISSUE TITLE
Develop a reporting tool

### ISSUE THREAD

**Issue by sr320** [OARS-SAFS/DEI#3]

**Comment by sr320** [comment]
Reporting tool has been develop and released to grad students
https://forms.gle/mmRmT1GTkNwaoF198

Once sent out to staff and post-docs, will close issue

**Comment by elpetrou** [comment]
Thank you for making this happen!!

**Comment by nclowell** [comment]
Is there a plan in development as to how these data will get used?

Unless people can connect their reporting to action, they may not take the risk of reporting or may not trust that reporting matters, etc.

**Comment by sr320** [comment]
We do have a plan that involves high level reporting back to the community. If action is requested it will be evident, sometime action is specifically not requested. 

The link to the tool will be on website in the next week.
