### ISSUE TITLE
Make SAFS Strategic Plan available on DEI Intranet

### ISSUE THREAD

**Issue by sr320** [OARS-SAFS/DEI#50]
based on faculty conversations and lack of access to relevant documentation

**Comment by JLGnotes** [comment]
It is available on Sharepoint [here](https://uwnetid.sharepoint.com/sites/safs/dei/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fsafs%2Fdei%2FShared%20Documents%2FSafs%20DEI%20strategic%20plan%5F2018%2D2021%2EMay2020%2Dfinal%2Epdf&parent=%2Fsites%2Fsafs%2Fdei%2FShared%20Documents).
