### ISSUE TITLE
Make DEI Committee "bylaws" available on DEI Intranet

### ISSUE THREAD

**Issue by sr320** [OARS-SAFS/DEI#52]
based on faculty conversations and lack of access to relevant documentation

**Comment by JLGnotes** [comment]
Diversity Terms of Reference (TOR) on Sharepoint [here](https://uwnetid.sharepoint.com/:w:/r/sites/safs/dei/_layouts/15/Doc.aspx?sourcedoc=%7B6299BB90-3F16-480B-B890-3B7EA01FDDA2%7D&file=Diversity%20TOR.docx&action=default&mobileredirect=true). 

SAFS E&I Committee 2019-2020 - Mission, Work Values, Charge on Sharepoint [here](https://uwnetid.sharepoint.com/sites/safs/dei/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fsafs%2Fdei%2FShared%20Documents%2FSAFS%20E%26I%20Committee%202019%2D2020%20%2D%20Mission%2C%20Work%20Values%2C%20Charge%2Epdf&parent=%2Fsites%2Fsafs%2Fdei%2FShared%20Documents). 

SAFS DEI list of documents on Sharepoint [here](https://uwnetid.sharepoint.com/sites/safs/dei/Shared%20Documents/Forms/AllItems.aspx).
