### ISSUE TITLE
Make hiring tool available on DEI Intranet

### ISSUE THREAD

**Issue by sr320** [OARS-SAFS/DEI#53]
based on faculty conversations and lack of access to relevant documentation

**Comment by JLGnotes** [comment]
The SAFS Diversity Hiring Tool handout is available at the bottom of the [SAFS Equity & Inclusion Committee webpage](https://fish.uw.edu/about/diversity-equity-and-inclusion/safs-equity-inclusion-committee/) under "Resources", and directly [here](https://fish.uw.edu/wp-content/uploads/sites/29/2020/04/SAFS.DiversityHiringTool_2020-04-22_FINAL.pdf). 

It is also available through SAFS DEI Sharepoint list of documents [here](https://uwnetid.sharepoint.com/sites/safs/dei/Shared%20Documents/Forms/AllItems.aspx), and directly [here](https://uwnetid.sharepoint.com/sites/safs/dei/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fsafs%2Fdei%2FShared%20Documents%2FSAFS%2EDiversityHiringTool%5F2020%2D04%2D22%5FFINAL%2Epdf&parent=%2Fsites%2Fsafs%2Fdei%2FShared%20Documents).
